name: Notify

on:
  push:
    branches:
      - main

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Get commit info
        id: commit
        run: |
          echo "Author: ${{ github.event.head_commit.author.name }}"
          echo "Commit Message: ${{ github.event.head_commit.message}}"

      - name: Send Message
        env:
          SERVER_URL: ${{ secrets.WHATSAPP_SERVER_URL }}
          API_KEY: ${{ secrets.WHATSAPP_API_KEY }}
          GROUP_ID: ${{ secrets.WHATSAPP_GROUP_ID }}
        run: |
          MESSAGE="Nuevo commit en el repo no olviden hacerse un pull :D
          Autor: ${{ github.event.head_commit.author.name }}
          Mensaje: ${{ github.event.head_commit.message }}
          Hash: ${{ github.event.head_commit.id }}"

          curl --request POST \
            --url $SERVER_URL \
            --header 'Content-Type: application/json' \
            --header 'Token: $API_KEY' \
            --data '{"group":"$GROUP_ID","message":"$MESSAGE"}'
